import type { Metadata } from 'next'
import './globals.css'
import GardenProvider from '@/garden/GardenProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <GardenProvider canvasSize={50} pixelScale={2}>
          {children}
        </GardenProvider>
      </body>
    </html>
  )
}
